export const baseURL="http://localhost:5000/api"
export const loginEndpoint="/auth/login"
export const signupEndpoint="/auth/register"
export const getInvoicesEndpoint="/invoices/"
export const updateStatus=(invoiceID)=>(`/invoices/${invoiceID}/status`)
export const uploadInvoice="/invoices/upload"
export const updateInvoice=(invoiceID)=>(`/invoices/${invoiceID}`)
export const deleteInvoice=(invoiceID)=>(`/invoices/${invoiceID}`)
export const myInvoices="/invoices/my-invoices"
export const chatBotEndpoint="/chat/"